/* Ample — Product data for all 8 product detail pages.
   Each product has hero copy, specs, feature bullets, callouts. */

const PRODUCTS = {
  'brake-pads': {
    slug: 'brake-pads',
    category: 'Braking',
    title: 'Ceramic Composite',
    title2: 'Brake Pads.',
    eyebrow: 'Performance Parts',
    goldStandard: true,
    sku: 'AMD1589C-32-H22M5',
    price: '€ 48,90',
    fit: 'BMW F30 · 2012–19 · Front axle',
    summary: 'Confidence features designed for daily driving, low noise, and predictable braking. Engineered for the commute and the canyon — consistent pedal feel, cleaner wheels, quieter stops.',
    hero: { emoji: '▧', label: 'Brake Pads set' },
    heroAsset: 'brake-pads',
    callouts: [
      { label: 'Ultra Low Dust', side: 'right', x: '68%', y: '12%' },
      { label: 'Anti-Noise Shim', side: 'left', x: '16%', y: '50%' },
      { label: 'Chamfered Edges', side: 'left', x: '14%', y: '78%' },
    ],
    features: [
      { icon: 'wind', title: 'Ultra Low Dust', body: 'Compared with metal brake pads, ceramic brake pads do not produce a lot of metal dust, keeping the wheels clean.' },
      { icon: 'activity', title: 'Anti Jitter', body: 'Vibration-damped friction plates eliminate pedal chatter, even on long descents.' },
      { icon: 'thermometer-sun', title: 'Heat-Resistant', body: 'Formulations tested to 800 °C brake fade. Built for track days — not just Tuesdays.' },
      { icon: 'leaf', title: 'Environment Protection', body: 'Copper-free, low-particulate ceramic binder. Meets ABE + ECE R90 environmental standards.' },
    ],
    bullets: [
      'Consistent pedal feel — built to deliver smooth engagement and predictable response across routine stop-and-go driving.',
      'Anti-noise shim — helps reduce squeal and keeps braking smooth under light and moderate use.',
      'Low dust formula — designed to help reduce visible brake dust so wheels stay cleaner in normal daily driving.',
      'Noise-controlled braking — engineered to help reduce squeal and vibration for quieter operation under everyday use.',
      'Friction materials — the right material blend for every vehicle, optimized for performance, comfort and longevity.',
      'Chamfered edges — precision-cut edges reduce noise and enhance flexibility and cooling under heavy use.',
    ],
    specs: [
      ['Friction μ', '0.42'],
      ['Max temp', '800 °C'],
      ['Compound', 'Ceramic composite'],
      ['Wear-in', '< 200 km'],
      ['Fitment', 'Front axle · 17.5 mm'],
      ['Certification', 'ABE · ECE R90'],
    ],
  },

  'calipers': {
    slug: 'calipers',
    category: 'Braking',
    title: 'Performance Caliper',
    title2: '& Rotor Assembly.',
    eyebrow: 'Braking',
    goldStandard: true,
    sku: 'CLP-7788-R',
    price: '€ 1 289,00',
    fit: 'Universal 330 mm · Track-ready',
    summary: 'Performance caliper-rotor assembly. Optimized thermal vents and multi-piston pressure scheme for street-to-track material.',
    heroAsset: 'caliper',
    callouts: [
      { label: 'Optimized Thermal Vents', side: 'right', x: '62%', y: '22%' },
      { label: 'Bolt-Pad Architecture', side: 'right', x: '68%', y: '44%' },
      { label: 'Multi-Piston Pressure', side: 'left', x: '14%', y: '68%' },
    ],
    features: [
      { icon: 'disc-3', title: 'Optimized Thermal Vents', body: 'Cross-drilled geometry extracts heat before it reaches the pad.' },
      { icon: 'settings-2', title: 'Bolt-Pad Architecture', body: '6-pot fixed caliper with monobloc body — zero flex under load.' },
    ],
    bullets: [
      'Forged aluminium monobloc body — 40% stiffer than stock.',
      '6 pistons per caliper, staggered 34/36/38 mm.',
      'Rotor: 2-piece floating, 330 × 30 mm.',
      'Includes stainless braided lines.',
    ],
    specs: [
      ['Pistons', '6-pot fixed'],
      ['Rotor', '330 × 30 mm · floating'],
      ['Body', 'Forged 7075-T6 aluminium'],
      ['Pad compound', 'Ceramic composite'],
      ['Weight saving', '−2.8 kg / axle'],
      ['Fitment', 'Universal · see bracket list'],
    ],
  },

  'radiators': {
    slug: 'radiators',
    category: 'Cooling',
    title: 'Core Radiator',
    title2: 'Assembly.',
    eyebrow: 'Cooling',
    goldStandard: true,
    sku: 'RAD-3310-V6',
    price: '€ 314,00',
    fit: 'VAG 2.0 TFSI · EA888',
    summary: 'An aluminium performance radiator welded onto a silicone fabrication core. Fitted onto a pressure contour for transmission, cooling, boom applications.',
    heroAsset: 'radiator',
    callouts: [
      { label: 'Bar-&-Plate Core', side: 'right', x: '62%', y: '22%' },
      { label: 'High-Capacity Design', side: 'right', x: '68%', y: '50%' },
      { label: 'Integrated Mount Points', side: 'right', x: '64%', y: '76%' },
    ],
    features: [
      { icon: 'layout-grid', title: 'High-Capacity Design', body: 'Dual-pass core holds 32% more coolant volume vs. OEM stamped radiator.' },
      { icon: 'anchor', title: 'Integrated Mount Points', body: 'Drop-in fitment. No bracketry, no modification to the core support.' },
    ],
    bullets: [
      'Dual-pass bar-and-plate core.',
      'TIG-welded end tanks, silicone hoses included.',
      '32% increased coolant capacity.',
      '−18 °C sustained delta under track load.',
    ],
    specs: [
      ['Core', 'Bar-and-plate, dual-pass'],
      ['Capacity', '6.4 L'],
      ['Material', '6061 aluminium · TIG-welded'],
      ['Pressure', '2.8 bar tested'],
      ['Delta vs OEM', '−18 °C sustained'],
      ['Fitment', 'EA888 Gen 2/3'],
    ],
  },

  'water-pump': {
    slug: 'water-pump',
    category: 'Cooling',
    title: 'High-Flow',
    title2: 'Water Pump.',
    eyebrow: 'Cooling',
    goldStandard: false,
    sku: 'WPU-2204-HF',
    price: '€ 189,00',
    fit: 'VAG EA888 · BMW N54/N55',
    summary: 'Forged impeller and composite housing. Delivers 18% higher coolant flow with a revised seal stack that survives sustained track loads.',
    heroAsset: 'water-pump',
    callouts: [
      { label: 'Forged 6-Blade Impeller', side: 'right', x: '62%', y: '26%' },
      { label: 'Ceramic Seal Stack', side: 'left', x: '14%', y: '52%' },
      { label: 'Composite Housing', side: 'right', x: '66%', y: '72%' },
    ],
    features: [
      { icon: 'wind', title: 'Forged impeller', body: '6-blade forged aluminium impeller. No cavitation above 7000 rpm.' },
      { icon: 'shield', title: 'Ceramic seal', body: 'Dual-lip ceramic face seal. Rated to 200,000 km duty cycle.' },
    ],
    bullets: [
      '+18% coolant flow vs. OEM plastic pump.',
      'Forged impeller — will not shatter at high rpm.',
      'Ceramic seal stack, 200,000 km service interval.',
      'Drop-in fitment, gasket included.',
    ],
    specs: [
      ['Flow rate', '+18% vs OEM'],
      ['Impeller', '6-blade forged Al'],
      ['Seal', 'Dual-lip ceramic'],
      ['Service life', '200,000 km'],
      ['Housing', 'Reinforced composite'],
      ['Fitment', 'EA888 · N54 · N55'],
    ],
  },

  'sensors': {
    slug: 'sensors',
    category: 'Electrical',
    title: 'Precision',
    title2: 'Sensor Suite.',
    eyebrow: 'Electrical',
    goldStandard: false,
    sku: 'SNS-4401-O2',
    price: '€ 124,00',
    fit: 'Universal · OEM+ spec',
    summary: 'Wideband oxygen, MAP, and crank-position sensors. Tighter tolerances than OEM, calibrated in our own dyno lab.',
    heroAsset: 'sensor',
    callouts: [
      { label: 'Laser-Welded Tip', side: 'right', x: '64%', y: '22%' },
      { label: 'Shielded Harness', side: 'left', x: '14%', y: '56%' },
      { label: 'Factory Calibrated', side: 'right', x: '68%', y: '78%' },
    ],
    features: [
      { icon: 'activity', title: 'Signal fidelity', body: 'Factory calibration to ±0.5% across the operating band.' },
      { icon: 'zap', title: 'Shielded harness', body: 'Braided shield + Teflon insulation. Immune to ignition noise.' },
    ],
    bullets: [
      'Wideband O₂, MAP, crank, cam — one catalog.',
      'Factory-calibrated to ±0.5%.',
      'Teflon-insulated, braid-shielded harness.',
      '2-year replacement warranty.',
    ],
    specs: [
      ['Accuracy', '±0.5% of reading'],
      ['Response', '< 100 ms'],
      ['Temp range', '−40 °C to 850 °C'],
      ['Connector', 'OEM-matched'],
      ['Shielding', 'Braided + Teflon'],
      ['Warranty', '2 years'],
    ],
  },

  'power-steering': {
    slug: 'power-steering',
    category: 'Steering',
    title: 'Electric Power',
    title2: 'Steering Rack.',
    eyebrow: 'Steering',
    goldStandard: true,
    sku: 'EPS-5520-R',
    price: '€ 1 489,00',
    fit: 'E-EPS universal · 3-stage tune',
    summary: 'Brushless motor, 3-stage assist mapping and re-manufactured rack housing. Direct CAN integration, no re-flash required.',
    heroAsset: 'power-steering',
    callouts: [
      { label: 'Brushless Motor', side: 'right', x: '62%', y: '24%' },
      { label: 'Hardened Rack', side: 'left', x: '12%', y: '56%' },
      { label: '3-Stage Assist Map', side: 'right', x: '68%', y: '76%' },
    ],
    features: [
      { icon: 'cpu', title: 'Brushless motor', body: 'Zero cogging, linear torque from 0 to 1200 rpm.' },
      { icon: 'sliders', title: '3-stage assist', body: 'Comfort / Sport / Track — selectable via steering-wheel toggle.' },
    ],
    bullets: [
      'Brushless — no brush wear, no EMI.',
      'Re-manufactured OEM housing, new internals.',
      '3-stage assist map, driver-selectable.',
      'Plug-and-play CAN. No re-flash.',
    ],
    specs: [
      ['Motor', 'Brushless · 48 V'],
      ['Assist modes', '3 (Comfort / Sport / Track)'],
      ['Rack', 'Hardened steel, rebuilt'],
      ['Integration', 'CAN plug-and-play'],
      ['Noise floor', '−12 dB vs OEM'],
      ['Warranty', '2 years'],
    ],
  },

  'starters': {
    slug: 'starters',
    category: 'Electrical',
    title: 'High-Torque',
    title2: 'Starter Motor.',
    eyebrow: 'Electrical',
    goldStandard: false,
    sku: 'STR-6601-HT',
    price: '€ 239,00',
    fit: 'Universal 12 V · 1.8 – 3.0 kW',
    summary: 'Rare-earth permanent-magnet starter with planetary reduction gear. 40% lighter and pulls 2.4 kW through a hot crank.',
    heroAsset: 'starter',
    callouts: [
      { label: 'Permanent-Magnet Core', side: 'right', x: '62%', y: '22%' },
      { label: 'Planetary Reduction', side: 'left', x: '14%', y: '54%' },
      { label: 'Heat-Shielded Solenoid', side: 'right', x: '66%', y: '78%' },
    ],
    features: [
      { icon: 'zap', title: 'High torque', body: '2.4 kW pull-through. Cranks hot V8s without drama.' },
      { icon: 'feather', title: 'Lightweight', body: '40% lighter than OEM cast-iron starter. 1.8 kg saved.' },
    ],
    bullets: [
      'Rare-earth permanent-magnet stator.',
      'Planetary gear reduction 3.4:1.',
      '2.4 kW sustained cranking.',
      'Heat-shielded solenoid for headers-close installs.',
    ],
    specs: [
      ['Power', '2.4 kW'],
      ['Reduction', '3.4:1 planetary'],
      ['Weight', '−40% vs OEM'],
      ['Heat shield', 'Ceramic-wrapped solenoid'],
      ['Voltage', '12 V'],
      ['Fitment', 'Universal + bracket kit'],
    ],
  },

  'filters': {
    slug: 'filters',
    category: 'Service',
    title: 'Multi-Stage',
    title2: 'Filter System.',
    eyebrow: 'Service',
    goldStandard: false,
    sku: 'FLT-8812-MS',
    price: '€ 58,00',
    fit: 'Universal · Oil · Air · Fuel',
    summary: 'Three-stage media: pleated synthetic, fine microfibre, and magnetic trap. Captures 99.4% of 8-micron particulate.',
    heroAsset: 'filter',
    callouts: [
      { label: '3-Stage Media', side: 'right', x: '64%', y: '24%' },
      { label: 'Magnetic Trap', side: 'left', x: '14%', y: '56%' },
      { label: 'Synthetic Pleat', side: 'right', x: '66%', y: '76%' },
    ],
    features: [
      { icon: 'filter', title: '3-stage capture', body: 'Pleated synthetic + microfibre + magnetic trap. 99.4% @ 8 µm.' },
      { icon: 'recycle', title: 'Serviceable', body: 'Replaceable element. The housing is yours for life.' },
    ],
    bullets: [
      '99.4% capture at 8 micron.',
      'Magnetic trap catches ferrous wear debris.',
      'Replaceable media — reusable housing.',
      'Oil, air, and fuel variants in one catalog.',
    ],
    specs: [
      ['Capture rate', '99.4% @ 8 µm'],
      ['Media', 'Synthetic + microfibre + magnet'],
      ['Service', 'Replaceable element'],
      ['Housing', 'Billet aluminium'],
      ['Pressure drop', '−22% vs paper'],
      ['Variants', 'Oil · Air · Fuel'],
    ],
  },
};

/* ---------------- Bulk catalog additions (brand-prefixed SKUs) ---------------- */

function makeProduct({ slug, brand, code, category, eyebrow, title, title2, fit, summary, heroAsset, sku, price, bullets, specs }) {
  return {
    slug, category, eyebrow: eyebrow || category,
    title, title2: title2 || '',
    goldStandard: false,
    sku: sku || `${brand}-${code}`,
    price: price || '€ —',
    fit: fit || 'Universal · OEM+ spec',
    summary: summary || `${title} ${title2 || ''}. OEM+ spec, ample brand. Reach out for fitment, batch availability and pricing.`.trim(),
    hero: { emoji: '▧', label: title },
    heroAsset,
    callouts: [],
    features: [],
    bullets: bullets || [
      'OEM+ tolerance — built to outlast the part it replaces.',
      'Drop-in fitment — no modification, no re-flash.',
      'Catalogued under our quality program — full traceability.',
      'Engineered, sourced and verified by the ample team.',
    ],
    specs: specs || [
      ['Brand', brand],
      ['Reference', code],
      ['Category', category],
      ['Quality', 'OEM+ spec'],
      ['Warranty', '2 years'],
      ['Fitment', 'See product card'],
    ],
  };
}

const NEW_PRODUCTS = [
  makeProduct({ slug: 'wiper-linkage', brand: 'Ado', code: 'ADO-WL-2210', category: 'Wipers', title: 'Wiper Linkage', title2: 'Assembly.', fit: 'Front · OEM bracket compatible', heroAsset: 'wiper-motor', price: '€ 96,00' }),
  makeProduct({ slug: 'wiper-motor', brand: 'Ado', code: 'ADO-WM-2211', category: 'Wipers', title: 'Wiper', title2: 'Motor.', fit: '12 V · 2-speed park-position', heroAsset: 'wiper-motor', price: '€ 142,00' }),
  makeProduct({ slug: 'oil-cooler', brand: 'AGC', code: 'AGC-OC-3308', category: 'Cooling', title: 'Oil', title2: 'Cooler.', fit: 'Stacked-plate · thermostatic', heroAsset: 'oil-cooler', price: '€ 184,00' }),
  makeProduct({ slug: 'tensioner', brand: 'ANT', code: 'ANT-TN-4402', category: 'Engine', title: 'Belt', title2: 'Tensioner.', fit: 'Auxiliary belt · spring-loaded', heroAsset: 'tensioner', price: '€ 78,00' }),
  makeProduct({ slug: 'starter', brand: 'Ast', code: 'AST-ST-6601', category: 'Electrical', title: 'Starter', title2: 'Motor.', fit: '12 V · 1.8–2.4 kW · gear-reduction', heroAsset: 'starter', price: '€ 198,00' }),
  makeProduct({ slug: 'water-pump-awn', brand: 'AWN', code: 'AWN-WP-2204', category: 'Cooling', title: 'Water', title2: 'Pump.', fit: 'OEM-housing · forged impeller', heroAsset: 'water-pump', price: '€ 112,00' }),
  makeProduct({ slug: 'blower-motor', brand: 'AYC', code: 'AYC-BM-5512', category: 'HVAC', title: 'Blower', title2: 'Motor.', fit: '12 V · cabin HVAC · multi-speed', heroAsset: 'blower-motor', price: '€ 124,00' }),
  makeProduct({ slug: 'lighting', brand: 'LEDS', code: 'LEDS-LH-7720', category: 'Lighting', title: 'LED', title2: 'Lighting.', fit: 'Headlight assemblies · DRL · indicator', heroAsset: 'lighting', price: '€ 248,00' }),
  makeProduct({ slug: 'ignition-coil', brand: 'LEN', code: 'LEN-IC-7740', category: 'Engine', title: 'Ignition', title2: 'Coil.', fit: 'Coil-on-plug · pencil style', heroAsset: 'ignition-coil', price: '€ 64,00' }),
  makeProduct({ slug: 'caliper-npc', brand: 'NPC', code: 'NPC-CL-7788', category: 'Braking', title: 'Brake', title2: 'Caliper.', fit: 'OEM rebuild · single-piston', heroAsset: 'caliper', price: '€ 168,00' }),
  makeProduct({ slug: 'compressor', brand: 'UAC', code: 'UAC-CP-9912', category: 'HVAC', title: 'A/C', title2: 'Compressor.', fit: 'R134a · 6-cyl swash-plate', heroAsset: 'compressor', price: '€ 412,00' }),
  makeProduct({ slug: 'exhaust', brand: 'UEC', code: 'UEC-EX-8801', category: 'Engine', title: 'Exhaust', title2: 'System.', fit: 'Cat-back · stainless 304', heroAsset: 'exhaust', price: '€ 528,00' }),
  makeProduct({ slug: 'gasket', brand: 'UEL', code: 'UEL-GK-8810', category: 'Engine', title: 'Gaskets', title2: '', fit: 'Multi-layer steel · OEM bore', heroAsset: 'gasket', price: '€ 56,00' }),
  makeProduct({ slug: 'abs-sensor', brand: 'UOL', code: 'UOL-AS-9901', category: 'Braking', title: 'ABS', title2: 'Sensor.', fit: 'Hall-effect · OE connector', heroAsset: 'sensor', price: '€ 48,00' }),
  makeProduct({ slug: 'pad-sensor', brand: 'UOL', code: 'UOL-PS-9902', category: 'Braking', title: 'Brake Pad', title2: 'Wear Sensor.', fit: 'Front · loop-break circuit', heroAsset: 'sensor', price: '€ 18,00' }),
  makeProduct({ slug: 'power-steering-pump', brand: 'UPM', code: 'UPM-PS-1102', category: 'Steering', title: 'Power Steering', title2: 'Pump.', fit: 'Hydraulic · vane-type', heroAsset: 'water-pump', price: '€ 286,00' }),
  makeProduct({ slug: 'radiator-urk', brand: 'URK', code: 'URK-RD-3310', category: 'Cooling', title: 'Cooling', title2: 'Radiator.', fit: 'Aluminium core · plastic tank', heroAsset: 'radiator', price: '€ 198,00' }),
  makeProduct({ slug: 'condenser', brand: 'URK', code: 'URK-CD-3311', category: 'HVAC', title: 'A/C', title2: 'Condenser.', fit: 'Parallel-flow · R134a / R1234yf', heroAsset: 'radiator', price: '€ 178,00' }),
  makeProduct({ slug: 'heater-core', brand: 'URK', code: 'URK-HC-3312', category: 'HVAC', title: 'Heater', title2: 'Core.', fit: 'Brass-tube · OEM dimensions', heroAsset: 'radiator', price: '€ 124,00' }),
  makeProduct({ slug: 'rack-pinion', brand: 'UTA', code: 'UTA-RP-1120', category: 'Steering', title: 'Rack', title2: '& Pinion.', fit: 'Re-manufactured · OE geometry', heroAsset: 'rack-pinion', price: '€ 689,00' }),
  makeProduct({ slug: 'air-filter', brand: 'AMP', code: 'AMP-AF-8801', category: 'Service', title: 'Air', title2: 'Filter.', fit: 'Pleated synthetic · drop-in', heroAsset: 'filter', price: '€ 22,00' }),
  makeProduct({ slug: 'cabin-filter', brand: 'AMP', code: 'AMP-CF-8802', category: 'Service', title: 'Cabin', title2: 'Filter.', fit: 'Activated carbon · HEPA-grade', heroAsset: 'filter', price: '€ 28,00' }),
];

NEW_PRODUCTS.forEach(p => { PRODUCTS[p.slug] = p; });

const PRODUCT_ORDER = [
  'brake-pads', 'calipers', 'caliper-npc', 'abs-sensor', 'pad-sensor',
  'radiators', 'radiator-urk', 'water-pump', 'water-pump-awn', 'oil-cooler',
  'compressor', 'condenser', 'heater-core', 'blower-motor',
  'sensors', 'starters', 'starter', 'ignition-coil', 'lighting',
  'wiper-motor', 'wiper-linkage',
  'tensioner', 'exhaust', 'gasket',
  'power-steering', 'power-steering-pump', 'rack-pinion',
  'filters', 'air-filter', 'cabin-filter',
];

Object.assign(window, { PRODUCTS, PRODUCT_ORDER });
